version: '3'
services:
  php:
    build: ./docker/php-fpm
    volumes:
      - ./project/:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  web:
    #build: ./docker/nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./project/:/var/www/html
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/docker.conf
    depends_on:
      - php

  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    volumes:
      - ./docker/databases:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - "3333:3306"